type: 'mel_band_roformer'

audio:
  chunk_size: 352800
  stft_n_fft: 2048
  stft_hop_length: 441
  stft_win_length: 2048
  stft_normalized: false
  stereo: true

model:
  dim: 384
  depth: 6
  num_stems: 1
  time_transformer_depth: 1
  freq_transformer_depth: 1
  num_bands: 60
  dim_head: 64
  heads: 8
  attn_dropout: 0
  ff_dropout: 0
  flash_attn: True
  sample_rate: 44100
  mask_estimator_depth: 2

training:
  instruments:
  - vocals
  - other

inference:
  num_overlap: 2
  batch_size: 1